observability:
  log_dir: "/var/log"

api:
  open_api:
    service_name: "SMS Groups API"
    swagger_ui_path: /swagger-ui
    version: "1"
  server:
    host: "127.0.0.1"
    port: 3000
  surrealdb:
    username: root
    password: root
    host: "127.0.0.1"
    port: 8000
    namespace: "default"
    database: "sms_groups"
