instrumentation:
  log_dir: "/var/log"

api:
  origin: "https://sms-groups.gibbz.cloud"
  open_api:
    service_name: "SMS Groups API"
    swagger_ui_path: /swagger-ui
    version: "1"
  server:
    host: "127.0.0.1"
    port: 3000
  mongodb:
    host: "127.0.0.1"
    port: 27017
    application: "SMS Groups"
    database: "sms_groups_api"
  root_credentials:
    organization:
      name: "Gotanet"
      authorization_server:
        issuer_url: https://localhost/oauth2/openid/sms_groups
        client_id: sms_groups
        client_password: zKTBRFwdsTdWex0Y5Vytjb2XfdHh9W7dJCt5TjzAbZ0M2q5C
