instrumentation:
  log_dir: "/var/log"

api:
  open_api:
    service_name: "SMS Groups API"
    swagger_ui_path: /swagger-ui
    version: "1"
  server:
    host: "127.0.0.1"
    port: 3000
  mongodb:
    host: "127.0.0.1"
    port: 27017
    application: "SMS Groups"
    database: "sms_groups_api"
  root_credentials:
    organization:
      name: "Gotanet"
      idp: "<keymaker>"
    admin:
      name: "admin"
      idp_id: "9442a1d3-c686-4e6d-869d-ed3f6265aad4"
